name: hydrogarden_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.8
  reactive_forms: ^18.1.1

  #state
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0

  # router
  go_router: ^16.2.1

  # persistence
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # api
  dio: '^5.2.0'
  openapi_generator_annotations: ^6.1.0
  hg_openapi:
    path: ../hg-openapi
  openapi:
    path: ../openapi
  
  # localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # json
  freezed_annotation: ^2.4.4
  json_annotation:  ^4.9.0

  # misc
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  openapi_generator: ^6.1.0
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  husky: ^0.1.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  